---
name: Ruby
'on':
  push:
    branches:
    - main
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    env:
      BUNDLE_WITH: development
    strategy:
      matrix:
        ruby-version:
        - '3.0'
        - '3.1'
        - '3.2'
        - '3.3'
        - head
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby-version }}"
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
